# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'SmarterTableCellsNib'
  app.device_family = :ipad
  app.delegate_class = "AppDelegate_iPad"
  app.files_dependencies 'app/complex_table_view_cell.rb' => 'app/nib_based_table_view_cell.rb'
end
